### ISSUE TITLE
VlcPlayer.VlcMediaPlayer.PixelHeight is wrong.

### ISSUE THREAD

**Issue by BitOfEiji** [higankanshi/Meta.Vlc#199]
![ss170331](https://cloud.githubusercontent.com/assets/26808091/24537410/d408f9fe-161c-11e7-8927-72b9279ab38c.png)
With 1920x1080 video VlcPlayer.VlcMediaPlayer.PixelHeight tells 1090 !
Not only with 1920x1080 videos, all height sizes are wrong.
Meta.Vlc  version 16.11.19 (or earlier)
Windows 10  Home (Japanese Edition)1607 build 14393.969 (.NET 4.6 ?)
This is all I could say .

**Comment by skirsten** [comment]
This happens because the `width` and `height` returned by the [`VideoFormatCallback`](https://github.com/higankanshi/Meta.Vlc/blob/6a571ddd17878da04b501e942efcb27c7b794972/Meta.Vlc/Interop/LibVlc.MediaPlayer.cs#L113) set by [`SetVideoFormatCallback`](https://github.com/higankanshi/Meta.Vlc/blob/6a571ddd17878da04b501e942efcb27c7b794972/Meta.Vlc/Interop/LibVlc.MediaPlayer.cs#L329) ([`libvlc_video_set_format_callbacks`](https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__media__player.html#gafbeef69fb76b4c4d6cb25145aee1ad99)) cannot be used as display width and height as they are currently beeing used in the [`VideoFormatCallback` handler](https://github.com/higankanshi/Meta.Vlc/blob/6a571ddd17878da04b501e942efcb27c7b794972/Meta.Vlc.Wpf/VlcPlayer.Events.cs#L335).

I found this [here](https://mailman.videolan.org/pipermail/vlc-devel/2014-March/097227.html):

> Why is height set to 290 rather than 270?

> Because the decoder wants 290 lines worth of memory, of which only the 270
> lines are visible.

> Fine, but then how do I know which lines are visible?

He never got an answer.

2 weeks ago [this issue](https://trac.videolan.org/vlc/ticket/15122) and earlier [this](https://trac.videolan.org/vlc/ticket/16789) got fixed so it should be possible to get the width and height via the `p_mes->u.video.i_height` and `p_mes->u.video.i_width` fields, but it seems like this patch is only in the nightly builds and we have to wait for _2.2.5_ to get the correct width and height.

But regardless the width and height returned by `VideoFormatCallback` must only be used for buffers so the `VideoDisplayContext` must be rewritten to work with different display and buffer sizes.
Also, it must currently be possible to get the correct display sizes as VLC is obviously capable of getting them.

I hope I or somebody else finds a fix for this prolem as this makes this otherwise awesome library unusable for me!

**Comment by skirsten** [comment]
I just verified that the PixelWidth and PixelHeight are indeed fixed in the [latest _2.2.5_ nightly](https://nightlies.videolan.org/build/win32/vlc-2.2.5-20170222-0303/), but before adjusting the height the video still got the wrong height returned from the VideoFormatCallback so you will see the size of the video jump from the wrong one to the right one and your form elements will jump with it.

**Comment by BitOfEiji** [comment]
Thank you. I understood the reason. I will look forward to seeing VLC fix release for a while.
