### ISSUE TITLE
Upgrate to VLC 3.0.4

### ISSUE THREAD

**Issue by phamvv** [higankanshi/Meta.Vlc#277]
I used your library, It works very well with VLC version 2.2.0
But I tried using vlc version 3.0.4, it lost some events: play, stop.
Version 3.0.4 can adjust Pitch Shift for audio. Can you update this function?
Thank you very much for this project.

**Comment by staor** [comment]
你好，higankanshi：
     首先非常感谢你以及贡献的库文件，使我在wpf中能直接使用vlc播放。其次想反馈我在应用中碰见的一些问题，望有空解答下，多谢！
1 发现vlc官方新版本3.0+的版本播放时占用CPU大致低于2%每个（1280*800），而2.0+的版本一直>6%，替换新版本的plugins+libvlccore.dll+libvlc.dll后发现不能播放，提示CreateMediaFromLocation异常，发现VlcMediaPlayerMediaChanged(object sender, MediaPlayerMediaChangedEventArgs e) 中e.NewMedia==null.可否升级Meta.Vlc.Wpf.dll兼容3.0+的vlc库文件

**Comment by higankanshi** [comment]
I'm working with 3.0 branch now, maybe it will release soon...

**Comment by jasonunbrokensoftware** [comment]
@higankanshi Thank you so much for your work. I worked with you in the past to help me fix some previous bugs and paid you a bounty. I'd be willing to pay you again in order to speed up a 3.x release. :)

Just let me know how best to get in touch. jason@unbrokensoftware.com is my email. Thanks again.

**Comment by higankanshi** [comment]
@jasonunbrokensoftware I have sent you an email. check it.

**Comment by higankanshi** [comment]
I have added libvlc 3.0 support just now, and I will update the release and Nuget packet as soon.

Check this [changelog](https://github.com/higankanshi/Meta.Vlc#20181231)
